"""GENERATED — do not edit. Regenerate with scripts/mine_findsecbugs.py.

Taint roles for third-party Java APIs, flattened from FindSecBugs'
taint configuration (github.com/find-sec-bugs/find-sec-bugs, LGPL-3.0).

Reference data about JDK/library API signatures only — none of FindSecBugs'
detector code or analysis logic is used here. Argument indices have been
converted from their reverse (stack-order) convention to left-to-right
parameter positions; see the script for the verification.
"""
from __future__ import annotations

# {owner_fqn: {method: (dangerous parameter positions,)}}
SINKS: dict[str, dict[str, tuple[int, ...]]] = {
    'com.amazonaws.services.simpledb.model.SelectRequest': {'<init>': (0,), 'withselectexpression': (0,)},
    'com.sun.jndi.ldap.LdapCtx': {'lookup': (0,), 'search': (0, 1)},
    'com.sun.org.apache.xpath.internal.XPathAPI': {'eval': (1,), 'selectnodeiterator': (1,), 'selectnodelist': (1,), 'selectsinglenode': (1,)},
    'com.unboundid.ldap.sdk.LDAPConnection': {'search': (0, 2)},
    'jakarta.activation.FileDataSource': {'<init>': (0,)},
    'java.io.File': {'<init>': (0, 1), 'createtempfile': (0, 1, 2)},
    'java.io.FileInputStream': {'<init>': (0,)},
    'java.io.FileOutputStream': {'<init>': (0,)},
    'java.io.FileReader': {'<init>': (0,)},
    'java.io.FileWriter': {'<init>': (0,)},
    'java.io.PrintStream': {'format': (0, 1), 'printf': (0, 1)},
    'java.io.PrintWriter': {'append': (0,), 'format': (0, 1, 2), 'print': (0,), 'printf': (0, 1, 2), 'println': (0,), 'write': (0,)},
    'java.io.RandomAccessFile': {'<init>': (0,)},
    'java.lang.ProcessBuilder': {'<init>': (0,), 'command': (0,)},
    'java.lang.Runtime': {'exec': (0, 1)},
    'java.lang.String': {'format': (0, 1)},
    'java.net.URL': {'getcontent': (-2,), 'openconnection': (-2, 0), 'openstream': (-2,)},
    'java.nio.file.Files': {'createtempdirectory': (0, 1), 'createtempfile': (0, 1, 2)},
    'java.nio.file.Path': {'of': (0, 1)},
    'java.nio.file.Paths': {'get': (0, 1)},
    'java.sql.Connection': {'nativesql': (0,), 'preparecall': (0,), 'preparestatement': (0,)},
    'java.sql.PreparedStatement': {'addbatch': (0,), 'execute': (0,), 'executelargeupdate': (0,), 'executequery': (0,), 'executeupdate': (0,)},
    'java.sql.Statement': {'addbatch': (0,), 'execute': (0,), 'executelargeupdate': (0,), 'executequery': (0,), 'executeupdate': (0,)},
    'java.util.Formatter': {'format': (0, 1)},
    'javax.activation.FileDataSource': {'<init>': (0,)},
    'javax.el.ExpressionFactory': {'createmethodexpression': (1,), 'createvalueexpression': (1,)},
    'javax.mail.Message': {'addheader': (0, 1), 'setdescription': (0,), 'setdisposition': (0,), 'setsubject': (0,)},
    'javax.naming.Context': {'lookup': (0,)},
    'javax.naming.directory.DirContext': {'lookup': (0,), 'search': (0, 1)},
    'javax.naming.directory.InitialDirContext': {'lookup': (0,), 'search': (0, 1)},
    'javax.naming.event.EventDirContext': {'lookup': (0,), 'search': (0, 1)},
    'javax.naming.ldap.InitialLdapContext': {'lookup': (0,), 'search': (0, 1)},
    'javax.naming.ldap.LdapContext': {'lookup': (0,), 'search': (0, 1)},
    'javax.naming.ldap.LdapName': {'<init>': (0,)},
    'javax.script.ScriptEngine': {'eval': (0,)},
    'javax.servlet.RequestDispatcher': {'forward': (-2,), 'include': (-2,)},
    'javax.servlet.ServletOutputStream': {'print': (0,), 'println': (0,)},
    'javax.servlet.http.Cookie': {'<init>': (0, 1), 'setvalue': (0,)},
    'javax.servlet.http.HttpServletResponse': {'addheader': (0, 1), 'senderror': (1,), 'setheader': (0, 1), 'setstatus': (1,)},
    'javax.servlet.http.HttpServletResponseWrapper': {'addheader': (0, 1), 'senderror': (1,), 'setheader': (0, 1), 'setstatus': (1,)},
    'javax.servlet.http.HttpSession': {'putvalue': (1,), 'setattribute': (1,)},
    'javax.servlet.jsp.JspWriter': {'append': (0,), 'print': (0,), 'println': (0,), 'write': (0,)},
    'javax.xml.transform.TransformerFactory': {'newtransformer': (0,)},
    'javax.xml.xpath.XPath': {'compile': (0,), 'evaluate': (0,)},
    'org.apache.commons.beanutils.BeanUtils': {'copyproperties': (1,), 'populate': (1,)},
    'org.apache.commons.beanutils.BeanUtilsBean': {'populate': (1,)},
    'org.apache.commons.httpclient.methods.GetMethod': {'<init>': (0,), 'setquerystring': (0,)},
    'org.apache.http.client.methods.HttpGet': {'<init>': (0,)},
    'org.apache.torque.util.BasePeer': {'executequery': (0,)},
    'org.apache.turbine.om.peer.BasePeer': {'executequery': (0,)},
    'org.apache.xml.security.utils.JDKXPathAPI': {'evaluate': (2,), 'selectnodelist': (2,)},
    'org.apache.xml.security.utils.XPathAPI': {'evaluate': (2,), 'selectnodelist': (2,)},
    'org.apache.xml.security.utils.XalanXPathAPI': {'evaluate': (2,), 'selectnodelist': (2,)},
    'org.apache.xpath.XPathAPI': {'eval': (1,), 'selectnodeiterator': (1,), 'selectnodelist': (1,), 'selectsinglenode': (1,)},
    'org.jboss.seam.log.Log': {'debug': (0,), 'error': (0,), 'fatal': (0,), 'info': (0,), 'trace': (0,), 'warn': (0,)},
    'org.owasp.encoder.tag.ForHtmlTag': {'dotag': (-2,)},
    'org.springframework.beans.BeanUtils': {'copyproperties': (0,)},
    'org.springframework.expression.ExpressionParser': {'parseexpression': (0,)},
    'org.springframework.expression.common.TemplateAwareExpressionParser': {'parseexpression': (0,)},
    'org.springframework.expression.spel.standard.SpelExpressionParser': {'parseexpression': (0,)},
    'org.springframework.jdbc.core.JdbcOperations': {'batchupdate': (0,), 'execute': (0,), 'query': (0,), 'queryforint': (0,), 'queryforlist': (0,), 'queryforlong': (0,), 'queryformap': (0,), 'queryforobject': (0,), 'queryforrowset': (0,), 'update': (0,)},
    'org.springframework.jdbc.core.JdbcTemplate': {'batchupdate': (0,), 'execute': (0,), 'query': (0,), 'queryforint': (0,), 'queryforlist': (0,), 'queryforlong': (0,), 'queryformap': (0,), 'queryforobject': (0,), 'queryforrowset': (0,), 'update': (0,)},
    'org.springframework.jdbc.core.PreparedStatementCreatorFactory': {'<init>': (0,), 'newpreparedstatementcreator': (0,)},
    'org.springframework.ldap.core.LdapOperations': {'list': (0,), 'lookup': (0,), 'search': (0, 1)},
    'org.springframework.ldap.core.LdapTemplate': {'list': (0,), 'lookup': (0,), 'search': (0, 1)},
}

# {owner_fqn: category}
SINK_CATEGORY: dict[str, str] = {
    'com.amazonaws.services.simpledb.model.SelectRequest': 'CWE-99/resource-injection',
    'com.sun.jndi.ldap.LdapCtx': 'CWE-90/ldap-injection',
    'com.sun.org.apache.xpath.internal.XPathAPI': 'CWE-643/xpath-injection',
    'com.unboundid.ldap.sdk.LDAPConnection': 'CWE-90/ldap-injection',
    'jakarta.activation.FileDataSource': 'CWE-22/path-traversal',
    'java.io.File': 'CWE-22/path-traversal',
    'java.io.FileInputStream': 'CWE-22/path-traversal',
    'java.io.FileOutputStream': 'CWE-22/path-traversal',
    'java.io.FileReader': 'CWE-22/path-traversal',
    'java.io.FileWriter': 'CWE-22/path-traversal',
    'java.io.PrintStream': 'CWE-134/format-string',
    'java.io.PrintWriter': 'CWE-79/xss',
    'java.io.RandomAccessFile': 'CWE-22/path-traversal',
    'java.lang.ProcessBuilder': 'CWE-78/command-injection',
    'java.lang.Runtime': 'CWE-78/command-injection',
    'java.lang.String': 'CWE-134/format-string',
    'java.net.URL': 'CWE-918/ssrf',
    'java.nio.file.Files': 'CWE-22/path-traversal',
    'java.nio.file.Path': 'CWE-22/path-traversal',
    'java.nio.file.Paths': 'CWE-22/path-traversal',
    'java.sql.Connection': 'CWE-89/sql-injection',
    'java.sql.PreparedStatement': 'CWE-89/sql-injection',
    'java.sql.Statement': 'CWE-89/sql-injection',
    'java.util.Formatter': 'CWE-134/format-string',
    'javax.activation.FileDataSource': 'CWE-22/path-traversal',
    'javax.el.ExpressionFactory': 'CWE-917/el-injection',
    'javax.mail.Message': 'CWE-93/smtp-header-injection',
    'javax.naming.Context': 'CWE-90/ldap-injection',
    'javax.naming.directory.DirContext': 'CWE-90/ldap-injection',
    'javax.naming.directory.InitialDirContext': 'CWE-90/ldap-injection',
    'javax.naming.event.EventDirContext': 'CWE-90/ldap-injection',
    'javax.naming.ldap.InitialLdapContext': 'CWE-90/ldap-injection',
    'javax.naming.ldap.LdapContext': 'CWE-90/ldap-injection',
    'javax.naming.ldap.LdapName': 'CWE-90/ldap-injection',
    'javax.script.ScriptEngine': 'CWE-94/code-injection',
    'javax.servlet.RequestDispatcher': 'CWE-552/file-disclosure',
    'javax.servlet.ServletOutputStream': 'CWE-79/xss',
    'javax.servlet.http.Cookie': 'CWE-113/response-splitting',
    'javax.servlet.http.HttpServletResponse': 'CWE-113/response-splitting',
    'javax.servlet.http.HttpServletResponseWrapper': 'CWE-113/response-splitting',
    'javax.servlet.http.HttpSession': 'CWE-501/trust-boundary',
    'javax.servlet.jsp.JspWriter': 'CWE-79/xss',
    'javax.xml.transform.TransformerFactory': 'CWE-611/xslt-injection',
    'javax.xml.xpath.XPath': 'CWE-643/xpath-injection',
    'org.apache.commons.beanutils.BeanUtils': 'CWE-915/bean-property-injection',
    'org.apache.commons.beanutils.BeanUtilsBean': 'CWE-915/bean-property-injection',
    'org.apache.commons.httpclient.methods.GetMethod': 'CWE-235/parameter-pollution',
    'org.apache.http.client.methods.HttpGet': 'CWE-235/parameter-pollution',
    'org.apache.torque.util.BasePeer': 'CWE-89/sql-injection',
    'org.apache.turbine.om.peer.BasePeer': 'CWE-89/sql-injection',
    'org.apache.xml.security.utils.JDKXPathAPI': 'CWE-643/xpath-injection',
    'org.apache.xml.security.utils.XPathAPI': 'CWE-643/xpath-injection',
    'org.apache.xml.security.utils.XalanXPathAPI': 'CWE-643/xpath-injection',
    'org.apache.xpath.XPathAPI': 'CWE-643/xpath-injection',
    'org.jboss.seam.log.Log': 'CWE-917/el-injection',
    'org.owasp.encoder.tag.ForHtmlTag': 'CWE-79/xss',
    'org.springframework.beans.BeanUtils': 'CWE-915/bean-property-injection',
    'org.springframework.expression.ExpressionParser': 'CWE-917/el-injection',
    'org.springframework.expression.common.TemplateAwareExpressionParser': 'CWE-917/el-injection',
    'org.springframework.expression.spel.standard.SpelExpressionParser': 'CWE-917/el-injection',
    'org.springframework.jdbc.core.JdbcOperations': 'CWE-89/sql-injection',
    'org.springframework.jdbc.core.JdbcTemplate': 'CWE-89/sql-injection',
    'org.springframework.jdbc.core.PreparedStatementCreatorFactory': 'CWE-89/sql-injection',
    'org.springframework.ldap.core.LdapOperations': 'CWE-90/ldap-injection',
    'org.springframework.ldap.core.LdapTemplate': 'CWE-90/ldap-injection',
}

# {owner_fqn: {method: (RECEIVER,)}} — return value is attacker-controlled.
# Methods upstream marks SAFE have been removed.
SOURCES: dict[str, dict[str, tuple[int, ...]]] = {
    'java.awt.TextComponent': {'getselectedtext': (-2,), 'gettext': (-2,)},
    'java.io.BufferedReader': {'readline': (-2,)},
    'java.io.Console': {'readline': (-2,)},
    'java.io.DataInputStream': {'readline': (-2,), 'readutf': (-2,)},
    'java.io.LineNumberReader': {'readline': (-2,)},
    'java.net.URL': {'getcontent': (-2,)},
    'java.sql.ResultSet': {'getnstring': (-2,), 'getstring': (-2,)},
    'javax.servlet.ServletRequest': {'getcontenttype': (-2,), 'getlocaladdr': (-2,), 'getlocalname': (-2,), 'getparameter': (-2,), 'getparametermap': (-2,), 'getparameternames': (-2,), 'getparametervalues': (-2,), 'getremotehost': (-2,), 'getservername': (-2,)},
    'javax.servlet.ServletRequestWrapper': {'getcontenttype': (-2,), 'getlocalname': (-2,), 'getparameter': (-2,), 'getparametermap': (-2,), 'getparameternames': (-2,), 'getparametervalues': (-2,), 'getremotehost': (-2,), 'getservername': (-2,)},
    'javax.servlet.http.Cookie': {'getcomment': (-2,), 'getdomain': (-2,), 'getname': (-2,), 'getpath': (-2,), 'getvalue': (-2,)},
    'javax.servlet.http.HttpServletRequest': {'getcontenttype': (-2,), 'getcookies': (-2,), 'getheader': (-2,), 'getheadernames': (-2,), 'getheaders': (-2,), 'getlocaladdr': (-2,), 'getlocalname': (-2,), 'getparameter': (-2,), 'getparametermap': (-2,), 'getparameternames': (-2,), 'getparametervalues': (-2,), 'getpathinfo': (-2,), 'getpathtranslated': (-2,), 'getquerystring': (-2,), 'getremotehost': (-2,), 'getremoteuser': (-2,), 'getrequesturi': (-2,), 'getrequesturl': (-2,), 'getservername': (-2,), 'getservletpath': (-2,)},
    'javax.servlet.http.HttpServletRequestWrapper': {'getcontenttype': (-2,), 'getcookies': (-2,), 'getheader': (-2,), 'getheadernames': (-2,), 'getheaders': (-2,), 'getlocalname': (-2,), 'getparameter': (-2,), 'getparametermap': (-2,), 'getparameternames': (-2,), 'getparametervalues': (-2,), 'getpathinfo': (-2,), 'getpathtranslated': (-2,), 'getquerystring': (-2,), 'getremotehost': (-2,), 'getremoteuser': (-2,), 'getrequesturi': (-2,), 'getrequesturl': (-2,), 'getservername': (-2,), 'getservletpath': (-2,)},
    'javax.swing.text.JTextComponent': {'getselectedtext': (-2,), 'gettext': (-2,)},
    'javax.ws.rs.core.MultivaluedMap': {'getfirst': (-2,)},
    'org.apache.commons.fileupload.FileItem': {'getname': (-2,)},
}

# {owner_fqn: {method: (positions whose taint reaches the RETURN value,)}}
# RECEIVER (-2) means the receiver's own taint carries through — which is how
# chained StringBuilder.append calls accumulate taint across a concatenation.
PROPAGATORS: dict[str, dict[str, tuple[int, ...]]] = {
    'flexjson.JSONSerializer': {'deepserialize': (0,), 'serialize': (0,)},
    'java.io.File': {'createtempfile': (0, 1, 2), 'getcanonicalpath': (-2,)},
    'java.lang.CharSequence': {'subsequence': (-2,)},
    'java.lang.Character': {'getname': (0,), 'tostring': (-2, 0)},
    'java.lang.Iterable': {'iterator': (-2,)},
    'java.lang.Object': {'clone': (-2,), 'tostring': (-2,)},
    'java.lang.String': {'concat': (-2, 0), 'format': (1, 2), 'intern': (-2,), 'join': (0, 1), 'replace': (-2, 1), 'replaceall': (-2, 1), 'replacefirst': (-2, 1), 'split': (-2,), 'subsequence': (-2,), 'substring': (-2,), 'tochararray': (-2,), 'tolowercase': (-2,), 'touppercase': (-2,), 'trim': (-2,), 'valueof': (0,)},
    'java.lang.StringBuffer': {'append': (-2, 0), 'insert': (-2,), 'subsequence': (-2,), 'substring': (-2,)},
    'java.lang.StringBuilder': {'append': (-2, 0), 'insert': (-2,), 'subsequence': (-2,), 'substring': (-2,)},
    'java.net.URI': {'create': (0,), 'getauthority': (-2,), 'getfragment': (-2,), 'gethost': (-2,), 'getpath': (-2,), 'getquery': (-2,), 'getrawauthority': (-2,), 'getrawfragment': (-2,), 'getrawpath': (-2,), 'getrawquery': (-2,), 'getrawschemespecificpart': (-2,), 'getrawuserinfo': (-2,), 'getscheme': (-2,), 'getschemespecificpart': (-2,), 'getuserinfo': (-2,), 'normalize': (-2,), 'parseserverauthority': (-2,), 'relativize': (-2, 0), 'resolve': (-2, 0), 'toasciistring': (-2,), 'tostring': (-2,), 'tourl': (-2,)},
    'java.net.URL': {'getauthority': (-2,), 'getfile': (-2,), 'gethost': (-2,), 'getpath': (-2,), 'getprotocol': (-2,), 'getquery': (-2,), 'getref': (-2,), 'getuserinfo': (-2,), 'toexternalform': (-2,), 'tostring': (-2,), 'touri': (-2,)},
    'java.text.MessageFormat': {'format': (0, 1)},
    'java.util.Arrays': {'tostring': (0,)},
    'java.util.Scanner': {'next': (-2,), 'nextline': (-2,)},
    'java.util.StringTokenizer': {'nexttoken': (-2,)},
    'javax.servlet.ServletContext': {'getnameddispatcher': (0,), 'getrealpath': (0,), 'getrequestdispatcher': (0,), 'getresource': (0,), 'getresourceasstream': (0,), 'getresourcepaths': (0,)},
    'javax.servlet.ServletRequest': {'getrealpath': (0,), 'getrequestdispatcher': (0,)},
    'javax.servlet.ServletRequestWrapper': {'getrealpath': (0,), 'getrequestdispatcher': (0,)},
    'javax.servlet.http.HttpServletRequest': {'getrealpath': (0,), 'getrequestdispatcher': (0,)},
    'javax.servlet.http.HttpServletRequestWrapper': {'getrealpath': (0,), 'getrequestdispatcher': (0,)},
    'kotlin.text.Regex': {'replace': (0,)},
}
